### ISSUE TITLE
Can't import to React

### ISSUE THREAD

**Issue by lokutech** [shikijs/shiki#110] opened 2020-12-23 18:28 UTC
Hi, I am not able to import shiki into a react app. I am getting `Uncaught TypeError: fs.readFileSync is not a function` error.
Here's my code for reference.

```
import './App.css'
import { useEffect, useState } from 'react'
import  shiki  from 'shiki'

shiki.getHighlighter({
  theme: 'nord'
}).then(highlighter => {
  console.log(highlighter.codeToHtml(`console.log('shiki');`, 'js'))
})
...
```

**Comment by frencojobs** [comment] 2021-01-10 12:20
Shiki is a server-side library, not for client-side. You have to use it in a NodeJS environment.

**Comment by orta** [comment] 2021-02-02 11:15
As of v0.9 - shiki can run in a browser, so maybe someone can work on validating it works in React?

**Comment by i9or** [comment] 2021-02-04 20:54
I was able use it with React.js, prepared a very basic demo with CRA: https://github.com/i9or/react-shiki-demo

Great work, thanks for the browser support!

Although should mention a few things, which I might not get right:

1. You need manually copy `languages`, `themes` and `dist/onigasm.wasm` somewhere in your app so it's available to browser. In case of CRA, it's `public` folder. But still I feel like it should be more straightforward, without any manual copy pasting. Again, I might be using package incorrectly :sweat_smile: 

2. I was not able to import `shiki` like that `import * as shiki from 'shiki'` or `import shiki from 'shiki'`, it just fails with
![image](https://user-images.githubusercontent.com/2616427/106952922-0f70ab80-6732-11eb-9f24-9be820318fac.png)
and
![image](https://user-images.githubusercontent.com/2616427/106952965-1d263100-6732-11eb-89d9-974ea9c4e8ff.png)
respectively.
Tried named import with no luck as well. Only directly importing js file worked:
    ```js
    import * as shiki from 'shiki/dist/index.js';
    ```

    My assumptions here are that either something wrong with CRA/Webpack resolving the packages or maybe because I have used TypeScript version of CRA template and just need to add some setting to `tsconfig.json`, I don't know :man_shrugging: 

3. I haven't seen this warning: https://github.com/shikijs/shiki/blob/a9ae1bd72900d7d56aec6390c5e8225e67165920/packages/shiki/src/loader.ts#L57
  By default shiki just tries to fetch content from some weird path not telling to set CDN:
  
    ![image](https://user-images.githubusercontent.com/2616427/106953899-41ced880-6733-11eb-8e07-fde07e36d653.png)

Any help would be appreciated.

**Comment by antfu** [comment] 2021-02-05 04:43
@i9or Thanks for the detailed description and repro.

For 2. and 3. should be fixed in the recent commits.

For 1. You can use your current solution or via third-party CDNs like unpkg or jsdelivr. If you'd like to bundle those file, you can do them this way:

```ts
import * as shiki from 'shiki';
import themeNord from 'shiki/themes/nord.json'
import langTS from 'shiki/languages/typescript.tmLanguage.json'
import langTSX from 'shiki/languages/tsx.tmLanguage.json'
import onigasm from 'arraybuffer-loader!shiki/dist/onigasm.wasm'

shiki.setOnigasmWASM(onigasm)
const highlighter = await shiki.getHighlighter({
  theme: 'nord',
  themes: [themeNord],
  langs: [{
    id: 'typescript',
    scopeName: langTS.scopeName,
    grammar: langTS,
    aliases: ['ts']
  }, {
    id: 'tsx',
    scopeName: langTSX.scopeName,
    grammar: langTSX
  }],
})
const highlightedCode = highlighter.codeToHtml(SAMPLE_CODE, 'tsx');
```

**Comment by antfu** [comment] 2021-02-05 04:44
@orta Fixed some bugs and types for this, can you have a look and maybe draft a new release? Thanks.

**Comment by orta** [comment] 2021-02-05 09:40
I can, and I have - this is shipped in 0.9.2 👍🏻

**Comment by i9or** [comment] 2021-02-05 22:41
Thanks for a quick fix and suggestions, @antfu.
Unfortunately I was not able to apply this line
```ts
import onigasm from 'arraybuffer-loader!shiki/dist/onigasm.wasm'
```
in CRA generated app, issues with the loader usage (something like "magic header not detected"). Haven't tried to eject the app though. Most probably a webpack configuration issue. Anyways, decided to quickly update my demo with minimal Webpack setup and now it works perfectly fine (again the link for anyone interested: https://github.com/i9or/react-shiki-demo)
Before migrating away from CRA I also noticed type mismatch for `grammar` and `themes` fields in `getHighlighter` options. I'll try to prepare a small reproducible demo for that and post it here. Probably tomorrow.
Thanks a lot for your work, gentlemen :bow:

**Comment by i9or** [comment] 2021-02-06 15:43
Was able to add TypeScript support with one minor issue. Once I set `"resolveJsonModule": true` in `tsconfig.json` my IDE shows this error:
![image](https://user-images.githubusercontent.com/2616427/107122720-b3289b80-6899-11eb-9a1d-17eb25e152bc.png)
Plus complains on `grammar` fields as well.
Here's an example: "resolveJsonModule": https://github.com/i9or/react-shiki-demo/tree/types-mismatch
Check `App.tsx` file.
It was possible to fix it quickly just removing the option above and declaring json as a module manually:
```ts
declare module "*.json";
```
Not a big issue for me personally, but still wanted to share.

**Comment by octref** [comment] 2021-04-07 04:06
The original issues seems to have been fixed.

**Closed by octref** 2021-04-07 04:06 UTC
Labels: bug
