### ISSUE TITLE
Module not found: Error: Can't resolve 'shiki/wasm' in 'D:\test\node_modules\shiki\dist\chunks'

### ISSUE THREAD

**Issue by xfstu** [shikijs/shiki#732] opened 2024-08-03 08:32 UTC
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Execute the installation command: npm install -D shiki, and then use the example code:
```javascript
<script>
import { codeToHtml } from 'shiki'
export default {
  data () {
    return {
    }
  },
  methods: {
    async test () {
      const code = 'const a = 1' // 输入代码片段
      const html = await codeToHtml(code, {
        lang: 'javascript',
        theme: 'vitesse-dark'
      })

      console.log(html) // 带有高亮显示的 HTML 字符串
    }
  },
  mounted () {

  }
}
</script>
```

cmd printing:
```txt
 ERROR  Failed to compile with 1 error                                                                          16:17:51

This dependency was not found:

* shiki/wasm in ./node_modules/shiki/dist/chunks/wasm-dynamic.mjs

To install it, you can run: npm install --save shiki/wasm
```
Browser print:
```txt
Failed to compile.

./node_modules/shiki/dist/chunks/wasm-dynamic.mjs
Module not found: Error: Can't resolve 'shiki/wasm' in 'D:\test\node_modules\shiki\dist\chunks'
```

Version:
vue:2.7.14
npm:16.15.1

### Reproduction

Reproducible

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by antfu** [comment] 2024-08-03 16:46
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-03 16:46 UTC

**Comment by XiayidanAlimu** [comment] 2024-10-28 09:08
I have the same issue with Vue, it seems that Shiki is a server side(node.js environment) solution, so we can not use it in client side like in vue/react...
