### ISSUE TITLE
Build failure in GH actions

### ISSUE THREAD

**Issue by sm1990** [shikijs/shiki#433] opened 2023-02-06 10:12 UTC
I'm getting the following error at https://github.com/ballerina-platform/ballerina-dev-website/actions/runs/4013706735/jobs/6893365358#step:5:62. Could you please check and let me know the fix.

**Comment by orta** [comment] 2023-02-06 10:42
Looks like a dupe of https://github.com/shikijs/shiki/issues/417 which still has the same recommendations I made in https://github.com/shikijs/shiki/issues/417#issuecomment-1385369068 - see if you can make a repro and submit that to the folks who maintain the language

**Comment by octref** [comment] 2023-02-09 18:00
You need to provide a reproducible case. Otherwise we can't help.

**Comment by sm1990** [comment] 2023-04-06 08:49
Hi,
Sorry for the delay. I was trying out few things on my own. Butt they didn't work. You can reproduce the issue [here](https://github.com/sm1990/shiki-test). Seems the issue occurs when there is lot of content. I removed half of the .md files and the GH action ran smoothly. Once I added them back, It failed again. Reducing the content is not an option for us :(. Hope you can find a solution. Let me know if you need anything else.

**Comment by sm1990** [comment] 2023-04-19 05:41
> I cloned and repo and ran `npm i` and `npm build` successfully:
> 
> <img alt="image" width="976" src="https://user-images.githubusercontent.com/4033249/231232923-490228d5-6de7-4876-aa64-090caad6bea4.png">
> 
> <img alt="image" width="976" src="https://user-images.githubusercontent.com/4033249/231232958-bf4f634c-880b-47d9-a8d3-7f486d0c2e40.png">
> 
> Seems it's a grammar error. Try the latest build that'll be released soon.

We can build it locally without an issue. Problem occurs when we try to build it via GitHub actions. I'll try with the latest Shiki build again.

**Comment by sm1990** [comment] 2023-05-08 04:19
@orta & @octref I tried the latest Shiki build 0.14.2. The issue still exist https://github.com/sm1990/shiki-test/actions/runs/4911293571/jobs/8769194445#step:5:61
Any solutions?

**Comment by orta** [comment] 2023-05-24 06:25
We both do open source in our spare time, which means you can get it when we make time for it. You're welcome to look into issues which affect you and try and help figure it out, but if there's no activity on your issue it's because nothing has changed from our side

**Comment by octref** [comment] 2023-05-27 20:14
These issues are related to ballerina grammar, not shiki itself. I see a lot of similarity between ballerina grammar and TypeScript. Maybe this issue's fix could help you: https://github.com/microsoft/TypeScript-TmLanguage/issues/567

**Comment by octref** [comment] 2023-05-28 05:29
I tried to debug but I think it's a build issue on your end, because
- This only happens to the pages in `swan-lake/why-ballerina`
- I checked the `[..slug].js` in `pages/learn/learn-the-language/` and `pages/why-ballerina`. They are almost identical
- I copied the content of `cloud-native.md` to `language-basics.md`, but the error only occurs for the first file not the second: https://github.com/octref/shiki-test/actions/runs/5102603243/jobs/9172263553

To summarize, this build error only happens for a subset of your blog post, and it's not because your content contains code that causes grammar errors. I don't have time to debug your whole build system.
I suggest that you do `npx create-next-app@latest`, try to only copy the setup for `swan-lake/why-ballerina` to figure out the issue. I don't think it's a shiki issue, but if you can find a minimal repro that says it's a shiki issue, open a new one with a minimal repro (not your whole website + build system).

You can see my investigation here: https://github.com/octref/shiki-test

**Closed by octref** 2023-05-28 05:29 UTC
Labels: need-more-info
