### ISSUE TITLE
@shikijs/monaco use monaco-editor-core will lose support monaco editor languages workers.

### ISSUE THREAD

**Issue by SuperManito** [shikijs/shiki#776] opened 2024-09-14 06:11 UTC
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

![image](https://github.com/user-attachments/assets/0867f3c7-c900-467c-b79e-48c3b2176592)
like twoslash

### Reproduction

.

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by SuperManito** [comment] 2024-09-14 06:17
your project have the same problem https://github.com/nuxt/learn.nuxt.com/blob/main/components/PanelEditorMonaco.client.vue

**Comment by antfu** [comment] 2024-09-14 21:07
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-09-14 21:07 UTC
