### ISSUE TITLE
Problems with errors reported during operation after installation

### ISSUE THREAD

**Issue by mewhz** [shikijs/shiki#456] opened 2023-03-30 13:19 UTC
I used npm i shiki's command，However, an error will be reported after the vue project is started.
![image](https://user-images.githubusercontent.com/48837161/228848200-7b5226ab-73b9-49a1-81cc-4ca6259b2383.png)
I configured the babel.config.js file for the project according to the online tutorial，But it didn't work.
![image](https://user-images.githubusercontent.com/48837161/228848449-f8898275-d0a0-49d1-8538-4f55f12695ac.png)
This is my project structure.
![image](https://user-images.githubusercontent.com/48837161/228848572-e7a9d5cd-f646-49cd-be6f-7d8b55960aba.png)
I don't know what to do, it has been bothering me for a long time. Thank you very much for your reply.

**Comment by orta** [comment] 2023-04-07 11:11
Perhaps you need to use a newer version of node? `?.` syntax came out quite a while ago now

**Comment by mewhz** [comment] 2023-04-07 12:56
> 也许您需要使用更新版本的节点？`?.`语法很早以前就出来了

Thank you for your reply. The node I am using is version 16, as shown in the figure. I feel that its version should be quite high. I have also used version 18 before, but all reported errors
![image](https://user-images.githubusercontent.com/48837161/230612527-bb47e53d-910b-41ee-89fa-2fae68ba530c.png)

**Comment by orta** [comment] 2023-04-07 20:31
Then maybe you need to update babel, as it also has to parse the .js file?

**Comment by mewhz** [comment] 2023-04-08 06:11
> 

Can you elaborate or give an example? I'm not sure I understand here, thank you very much

**Comment by mewhz** [comment] 2023-04-08 06:11
> Then maybe you need to update babel, as it also has to parse the .js file?

Can you elaborate or give an example? I'm not sure I understand here, thank you very much

**Comment by mewhz** [comment] 2023-04-12 02:42
> 尝试配置加载程序，以便在您的配置无法处理 esm 时`dist/index.js`不加载`dist/index.esm.js`。

May I ask if you could provide some examples? I don't quite understand this configuration here, thank you very much

**Comment by octref** [comment] 2023-04-13 16:28
It would be easier if you can use vue-cli to create a brand new project, make a git commit, make the changes that would reproduce this problem, commit again, and then share the project on GitHub with me.

**Comment by mewhz** [comment] 2023-04-25 01:54
> It would be easier if you can use vue-cli to create a brand new project, make a git commit, make the changes that would reproduce this problem, commit again, and then share the project on GitHub with me.

Thank you very much for your help. I have created a warehouse replication issue and invited you to participate. Could you please help solve the problem

**Comment by octref** [comment] 2023-05-27 18:08
Hey @mewhz, I had been busy – can you share with me the repo again? Many thanks.

**Comment by mewhz** [comment] 2023-05-28 07:17
> Hey @mewhz, I had been busy – can you share with me the repo again? Many thanks.

Of course, I would love to. Thank you for your help

**Comment by antfu** [comment] 2024-01-26 18:28
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-01-26 18:28 UTC
Labels: need-more-info
