### ISSUE TITLE
Describe the bug here

### ISSUE THREAD

**Issue by 321paranoiawhy** [shikijs/shiki#708] opened 2024-06-24 08:09 UTC
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Such code in `vitepress`:

````md
```vue twoslash :line-numbers
<script setup lang="ts">
import {ref} from 'vue';

const message = ref('Hello world!');
</script>
```
````

code block line numbers would be from 1 to 2, rather than from 1 to 5, [see here](https://321paranoiawhy.github.io/knowledge-base/TODO#bug)

### Reproduction

````md ```vue twoslash :line-numbers <script setup lang="ts"> import {ref} from 'vue';  const message = ref('Hello world!'); </script> ``` ````

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by 321paranoiawhy** [comment] 2024-06-24 08:12
I have already open an issue in [vitepress](https://github.com/vuejs/vitepress/issues/3972).

This is current behavior:

![](https://private-user-images.githubusercontent.com/100689670/341438413-6c2abc06-a711-482a-bd08-9a6135364cba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTY3MTUsIm5iZiI6MTcxOTIxNjQxNSwicGF0aCI6Ii8xMDA2ODk2NzAvMzQxNDM4NDEzLTZjMmFiYzA2LWE3MTEtNDgyYS1iZDA4LTlhNjEzNTM2NGNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwODA2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2FjZDdmYzhmODJhNzA5NzBiNzRmNTdlZTY5NjdkOTZmZDkyM2ZmNDRlZTkzZGYyZTA3ODQ1YmRhYzUwNTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tl8j9BfCSVmVpsW4F3lMhxMELHYY-Zpfqsuzq-us3_I)

**Comment by antfu** [comment] 2024-06-24 08:36
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-06-24 08:36 UTC
