### ISSUE TITLE
Infinite loop when parsing unclosed ansi string

### ISSUE THREAD

**Issue by Hoofoo-WHU** [shikijs/shiki#517] opened 2023-09-06 09:36 UTC
The root cause of this bug appears to be related to this [issue](https://github.com/blake-mealey/ansi-sequence-parser/issues/1), which has already been resolved. 
It's possible that updating to the latest version of the dependency could fix this issue in Shiki.

**Comment by antfu** [comment] 2024-01-26 20:53
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-01-26 20:53 UTC

**Comment by undefined-moe** [comment] 2024-07-24 18:18
got a repro https://jsfiddle.net/7rLk5fqa/1/ :

```ts
import { codeToHtml } from 'https://esm.sh/shiki@1.0.0';

async function main() {
  const options = {
    lang: 'ansi',
    theme: 'github-light',
  };
  document.body.innerHTML = await codeToHtml('this works', options);
  document.body.innerHTML = await codeToHtml(`but this doesn't
[01m[Kfoo.cc:[m[K In function ‘[01m[Kint[01;32m[K main[m[K()[m[K’:
[01m[Kfoo.cc:8:13:[m[K [01;31m[Kerror: [m[Kexpected ‘[01m[K;[m[K’ before ‘[01m[K}[m[K’ token
    8 |     return 0
      |             [01;31m[K^[m[K
      |             [32m[K;[m[K
    9 | [32m[K}[m[K
      | [32m[K~[m[K            
`, options);
}

main();
```

(base64 encoded payload)

```
G1swMW0bW0tmb28uY2M6G1ttG1tLIEluIGZ1bmN0aW9uIOKAmBtbMDFtG1tLaW50G1swMTszMm0b
W0sgbWFpbhtbbRtbSygpG1ttG1tL4oCZOgogICAgG1swMW0bW0tmb28uY2M6ODoxMzobW20bW0sg
G1swMTszMW0bW0tlcnJvcjogG1ttG1tLZXhwZWN0ZWQg4oCYG1swMW0bW0s7G1ttG1tL4oCZIGJl
Zm9yZSDigJgbWzAxbRtbS30bW20bW0vigJkgdG9rZW4KICAgICAgICA4IHwgICAgIHJldHVybiAw
CiAgICAgICAgICB8ICAgICAgICAgICAgIBtbMDE7MzFtG1tLXhtbbRtbSwogICAgICAgICAgfCAg
ICAgICAgICAgICAbWzMybRtbSzsbW20bW0sKICAgICAgICA5IHwgG1szMm0bW0t9G1ttG1tLCiAg
ICAgICAgICB8IBtbMzJtG1tLfhtbbRtbSw==
```
