### ISSUE TITLE
[BUG] Bug with vitepress integration

### ISSUE THREAD

**Issue by kravetsone** [shikijs/shiki#578] opened 2024-02-07 16:41 UTC
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

example from docs:
```ts
// .vitepress/theme/index.ts
import Theme from 'vitepress/theme'
import TwoslashFloatingVue from '@shikijs/vitepress-twoslash/client'
import '@shikijs/vitepress-twoslash/style.css'
import type { EnhanceAppContext } from 'vitepress'

export default {
  extends: Theme,
  enhanceApp({ app }: EnhanceAppContext) {
    app.use(TwoslashFloatingVue) // error here

  },
}
```
It's throw error for me(
```
Аргумент типа "typeof import("z:/PROJECTS/node-ts/GRAMIO/documentation/node_modules/@shikijs/vitepress-twoslash/dist/index")" нельзя назначить параметру типа "Plugin<[]>".ts(2345)
```

if i use `rendererFloatingVue` it's works! But when i hover to something nothing happens...

```ts
export default {
	extends: Theme,
	enhanceApp({ app }: EnhanceAppContext) {
		app.use(TwoslashFloatingVue.rendererFloatingVue);
	},
};
```

![image](https://github.com/shikijs/shiki/assets/57632712/aaff3fd4-1cb5-4e01-8934-1258570df268)

### Reproduction

example from docs

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment] 2024-02-07 23:16
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-02-07 23:16 UTC

**Comment by kravetsone** [comment] 2024-02-07 23:20
> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
> Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

You can see it here - https://github.com/gramiojs/documentation

**Comment by kravetsone** [comment] 2024-02-08 11:46
> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

it work's fine with that but TS error exists....
![image](https://github.com/shikijs/shiki/assets/57632712/7b214588-73a0-4e1f-a345-6f74427cbb02)

  "@shikijs/vitepress-twoslash": "^1.0.0",
  "vitepress": "^1.0.0-rc.42"

**Comment by antfu** [comment] 2024-02-08 12:44
Then it's a type error rather than a bug

**Comment by kravetsone** [comment] 2024-02-08 13:25
> Then it's a type error rather than a bug

then I didn't think of ignoring the type error... sorry
