### ISSUE TITLE
Row of `language-*` on a single `code` element

### ISSUE THREAD

**Issue by piscopancer** [shikijs/shiki#685] opened 2024-05-28 16:58 UTC
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

![image](https://github.com/shikijs/shiki/assets/109352196/e5a67c48-b949-4559-9f21-44df6275df89)

shiki is used on the server as a rehype plugin
my config
```ts
export const rehypeShikiOptions = {
  themes: { light: theme },
  langs,
  addLanguageClass: true,
} satisfies RehypeShikiOptions
```
then it is used in MDX remote server component
```tsx
import { rehypeShikiOptions } from '@/app/shiki'
import shiki from '@shikijs/rehype'
import { MDXRemote } from 'next-mdx-remote/rsc'
import remarkGfm from 'remark-gfm'
import remarkUnwrapImages from 'remark-unwrap-images'
import { components } from '.'

export function ServerMDX(props: { text: string }) {
  return (
    <MDXRemote
      source={props.text}
      options={{
        mdxOptions: {
          remarkPlugins: [remarkGfm, remarkUnwrapImages],
          rehypePlugins: [[shiki, rehypeShikiOptions]],
        },
      }}
      components={components}
    />
  )
}
```
I did not do any sort of modifications, however when there are more than 1 code blocks in my md/mdx, shiki decides to apply multiple languages to a single `code` element

### Reproduction

-

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment] 2024-05-31 12:44
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-05-31 12:44 UTC
