### ISSUE TITLE
lang attribute breaks formatting

### ISSUE THREAD

**Issue by lgraubner** [shikijs/shiki#547] opened 2023-12-14 08:50 UTC
I want to format a Svelte code block which uses Typescript.

```svelte
<script lang="ts">
	// src/routes/+layout.svelte

	import * as Fathom from 'fathom-client';
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';
	import { page } from '$app/stores';

	onMount(() => {
		Fathom.load('YAGZBRQY', {
			// do not track load as page view, happens
			// via trackRouteChange automatically
			auto: false
		});
	});

	function trackRouteChange() {
		if (browser) {
			Fathom.trackPageview();
		}
	}

	$: $page.url.pathname, trackRouteChange();
</script>

<slot />
```

But as soon as `lang="ts"` is present, the formatting in the script block is messed up.
<img width="714" alt="Screenshot 2023-12-14 at 09 46 07" src="https://github.com/shikijs/shiki/assets/2519959/a52528f0-251e-4160-93ec-ad5e553f4bd7">

Removing it "solves" the problems. Other values like `ts` do not seem to be affected. It should look like this:
<img width="733" alt="Screenshot 2023-12-14 at 09 45 19" src="https://github.com/shikijs/shiki/assets/2519959/02a4fe0a-1746-4894-983e-d8de04d3956a">

**Comment by antfu** [comment] 2024-01-26 18:05
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2024-01-26 18:12 UTC
