### ISSUE TITLE
Cypress test failed with Shiki

### ISSUE THREAD

**Issue by ragnaroksj** [shikijs/shiki#735] opened 2024-08-06 17:53 UTC
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

When I write the e2e test(I use cypress), I get following error:
```
TypeError: The following error originated from your test code, not from Cypress.
  > Cannot read properties of undefined (reading 'VSCODE_TEXTMATE_DEBUG')
When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
Cypress could not associate this error to any specific test.
We dynamically generated a new test to display this failure.
    at <unknown> (http://localhost:4200/__cypress/src/node_modules/.vite/abc/deps/shiki.js?v=45528b20:1586:63)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:4200/__cypress/runner/cypress_runner.js:3486:19)
    at Promise._then (http://localhost:4200/__cypress/runner/cypress_runner.js:1239:17)
    at Promise.then (http://localhost:4200/__cypress/runner/cypress_runner.js:1132:17)
    at runScriptsFromUrls (http://localhost:4200/__cypress/runner/cypress_runner.js:110842:136)
    at Object.runScripts (http://localhost:4200/__cypress/runner/cypress_runner.js:110883:12)
    at $Cypress.onSpecWindow (http://localhost:4200/__cypress/runner/cypress_runner.js:40889:67)
    at <unknown> (http://localhost:4200/__cypress/iframes/index.html?specPath=/abc/libs/components/react/src/code-snippet.cy.tsx:75:17)
﻿```
Does anyone have any idea about this?

### Reproduction

Install shiki and cypress frame. Run cypress test with the component that using shiki..

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment] 2024-08-12 12:47
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-12 12:47 UTC

**Comment by zero-one-code** [comment] 2024-09-14 03:01
你好，我也遇到同样的问题。
[最小重现](https://github.com/zero-one-code/vue3-vite-ts.git)

看起来应该是依赖包 `@shikijs/vscode-textmate` 中[`process.env['VSCODE_TEXTMATE_DEBUG']`](https://github.com/shikijs/vscode-textmate/blob/8d2e84a3aad21afd6b08fd53c7acd421c7f5aa44/src/debug.ts#L6)引发的问题
