### ISSUE TITLE
Error: with Next.js app

### ISSUE THREAD

**Issue by maccman** [shikijs/shiki#461] opened 2023-04-19 02:35 UTC
I'm trying to use shiki with Next.js's app setup. 

Sporadically I'm getting this error. It seems non-deterministic. 

```


at /vercel/path0/node_modules/vscode-oniguruma/release/main.js:1:3101
--
22:34:01.941 | at new u (/vercel/path0/node_modules/vscode-oniguruma/release/main.js:1:3150)
22:34:01.941 | at n.createOnigScanner (/vercel/path0/node_modules/vscode-oniguruma/release/main.js:1:4984)
22:34:01.941 | at Object.createOnigScanner (/vercel/path0/node_modules/@maccman/shiki/dist/index.js:1926:34)
22:34:01.941 | at g.createOnigScanner (/vercel/path0/node_modules/vscode-textmate/release/main.js:1:4532)
22:34:01.941 | at new m (/vercel/path0/node_modules/vscode-textmate/release/main.js:1:47463)
22:34:01.941 | at g.compile (/vercel/path0/node_modules/vscode-textmate/release/main.js:1:46704)
22:34:01.941 | at g.compileAG (/vercel/path0/node_modules/vscode-textmate/release/main.js:1:47238)
22:34:01.941 | at u.compileAG (/vercel/path0/node_modules/vscode-textmate/release/main.js:1:38683)
22:34:01.941 | at l (/vercel/path0/node_modules/vscode-textmate/release/main.js:1:22586)


Error: \(([^\(\)]\|(\(([^\(\)]\|\([^\(\)]*\))*\)))*\))\|(\[([^\[\]]\|(\[([^\[\]]\|\[[^\[\]]*\])*\]))*\]))([^=<>]\|=[^<]\|\<\s*(((const\s+)?[_$[:alpha:]])\|(\{([^\{\}]\|(\{([^\{\}]\|\{[^\{\}]*\})*\}))*\})\|(\(([^\(\)]\|(\(([^\(\)]\|\([^\(\)]*\))*\)))*\))\|(\[([^\[\]]\|(\[([^\[\]]\|\[[^\[\]]*\])*\]))*\]))([^=<>]\|=[^<]\|\<\s*(((const\s+)?[_$[:alpha:]])\|(\{([^\{\}]\|(\{([^\{\}]\|\{[^\{\}]*\})*\}))*\})\|(\(([^\(\)]\|(\(([^\(\)]\|\([^\(\)]*\))*\)))*\))\|(\[([^\[\]]\|(\[([^\[\]]\|\[[^\[\]]*\])*\]))*\]))([^=<>]\|=[^<])*\>)*\>)*>\s*)?                                                                                 # typeparameters
--
22:29:48.533 | \(\s*(\/\*([^\*]\|(\*[^\/]))*\*\/\s*)*(([_$[:alpha:]]\|(\{([^\{\}]\|(\{([^\{\}]\|\{[^\{\}]*\})*\}))*\})\|(\[([^\[\]]\|(\[([^\[\]]\|\[[^\[\]]*\])*\]))*\])\|(\.\.\.\s*[_$[:alpha:]]))([^()\'\"\`]\|(\(([^\(\)]\|(\(([^\(\)]\|\([^\(\)]*\))*\)))*\))\|(\'([^\'\\]\|\\.)*\')\|(\"([^\"\\]\|\\.)*\")\|(\`([^\`\\]\|\\.)*\`))*)?\)   # parameters
22:29:48.533 | (\s*:\s*([^<>\(\)\{\}]\|\<([^<>]\|\<([^<>]\|\<[^<>]+\>)+\>)+\>\|\([^\(\)]+\)\|\{[^\{\}]+\})+)?                                                                        # return type
22:29:48.533 | \s*=>
```

**Comment by octref** [comment] 2023-04-29 00:28
Why is it non-deterministic? Does it happen randomly for the same code highlighted? Can you get a minimal repro?

**Comment by diegohaz** [comment] 2023-05-06 00:02
I get a similar error during `next dev`. As @maccman mentioned, it happens sporadically. I've never been able to reproduce it consistently. That's why I didn't open an issue.

I can only get rid of the error by restarting the dev server until it happens again after minutes or hours.

<img width="998" alt="screenshot of the error described above" src="https://user-images.githubusercontent.com/3068563/236586478-48ca4197-dcee-4804-bc04-c8be5af4462f.png">

**Comment by tannerabread** [comment] 2023-05-11 13:44
Getting the same error in my Next.js app using the new app router functionality

**Comment by octref** [comment] 2023-05-27 18:06
Hey @tannerabread, does it happen with consistently with that blog post? Can you post a minimal repro?

**Comment by tannerabread** [comment] 2023-05-30 14:12
@octref it was consistent enough that I couldn't build my app, locally or on Vercel

It was inconsistent with most posts I was adding to my project but seemed really consistent with [this markdown file](https://github.com/tannerabread/nextjs-digital-garden/blob/main/app/blog/posts/setup.mdx). Sometimes the project would build if I removed that file and sometimes not

I was finally able to get around it by switching to MDX vs .md files and using shiki in conjunction with rehype-pretty-code and a completely different architecture as [outlined here](https://bannon.cloud/blog/mdx)

A big key in the solution seemed to be including the plugins with `.next.config.mjs` as shown in the [new docs for Next.js app router](https://nextjs.org/docs/app/building-your-application/configuring/mdx#remark-and-rehype-plugins)

**Comment by antfu** [comment] 2024-01-26 20:55
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-01-26 20:55 UTC
Labels: need-more-info
