### ISSUE TITLE
Build failure due to 'Failed to highlight code block with language' 

### ISSUE THREAD

**Issue by nandhiniG** [shikijs/shiki#839] opened 2024-11-19 06:43 UTC
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

We use a Next.js app for our documentation website, with Shiki (current version: 1.22.2) for syntax highlighting. However, we frequently encounter the following CI error, causing delays in the PR process:  

![AnySnap 19 Nov 2024 at 12_10_32 PM](https://github.com/user-attachments/assets/f396c199-0206-4659-8c70-833ab1c874d4)  

The error typically involves languages such as `jsx`, `tsx`, `typescript`, or `javascript`. Upgrading to the latest version of Shiki did not resolve the issue, and the error persists.

### Reproduction

Build error 

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment] 2024-11-20 14:58
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-11-20 14:58 UTC
