### ISSUE TITLE
Cannot load WASM with Cloudflare Worker

### ISSUE THREAD

**Issue by hckhanh** [shikijs/shiki#590] opened 2024-02-17 14:09 UTC
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

I receive this error:

```
Uncaught TypeError: WebAssembly.instantiate(): Import #0 module="env": module is not an object or function
```

When I try to import wasm module with CF worker. I think something is wrong with the WASM file.

### Reproduction

I will add later

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment] 2024-02-18 07:08
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-02-18 07:08 UTC

**Comment by AleksandrHovhannisyan** [comment] 2024-12-05 00:22
Hi @antfu, sorry to necro this issue, but I ran into a similar issue as OP and put together a minimal repro here:

https://github.com/AleksandrHovhannisyan/shikijs-markdownit-cloudflare-wasm-bug

It's for a slightly different error message than the one OP saw, but it also seems to be related to WASM and is only reproducible in a Cloudflare worker. **Should I open a new issue, or should we re-open this one?**

```
✘ [ERROR] service core:user:shikijs-markdownit-cloudflare-wasm-bug: Uncaught CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder

    at null.<anonymous> (index.js:5164:26) in getWasmInstance
    at null.<anonymous> (index.js:7263:42)
``` 

I think it's because of this:

https://github.com/shikijs/shiki/blob/64f1453c4ab6b27c95e7129324664cde31ad0d40/packages/markdown-it/src/index.ts#L4

https://github.com/shikijs/shiki/blob/64f1453c4ab6b27c95e7129324664cde31ad0d40/packages/core/src/constructors/bundle-factory.ts#L90

In that file, at the top, it looks like there's an import related to WASM:

https://github.com/shikijs/shiki/blob/64f1453c4ab6b27c95e7129324664cde31ad0d40/packages/core/src/constructors/bundle-factory.ts#L27

So my guess is that somehow it's not getting properly tree-shaken.

**Comment by antfu** [comment] 2024-12-05 02:21
I believe it's mentioned here https://shiki.style/guide/install#cloudflare-workers that CF needs fine-grain bundle with explicit wasm import. Meaning that for markdown-it, you also need https://shiki.style/packages/markdown-it#fine-grained-bundle.

Please do not comment under a closed issue. Feel free to open a new one linking back.

**Comment by AleksandrHovhannisyan** [comment] 2024-12-05 02:42
Oh! Sorry about that, not sure how I missed that in the docs.
